---
title: 'Northrop Grumman: Case Study'
output: html_document
---

```{r setup}
setwd("C:/Users/chari/Desktop/CSET/AI Hype Project")
rm(list=ls())
library(tidyverse)
```


What majors are the most in demand? (2019)
```{r}
ng_major <- read_csv("ng_major.csv")

ng_major <- arrange(ng_major, desc(job_count))

# Remove null majors
ng_major <- filter(ng_major, !is.na(ng_major$major))

# Horizontal bar graph, take the top 10 majors
ggplot(ng_major[1:10,], aes(x = reorder(major, job_count), y = job_count)) + 
  geom_bar(stat = "identity") + 
  theme_gray(base_size = 15) +
  labs(title = "Top 10 Majors in Demand at Northrop Grumman (2019)",
       x = "Major",
       y = "Job Count") +
  coord_flip()
```


What kind of occupation fields is the company focusing on? What are the most popular majors for each occupation field?
```{r}
ng_field <- read_csv("ng_field.csv")

ng_field <- arrange(ng_field, DETAIL, desc(job_count))

# Bar graph of total job postings in each occupation field
ng_field %>%
  group_by(DETAIL) %>%
  summarise(total = sum(job_count)) %>%
  ggplot(aes(x = reorder(DETAIL, -total), y = total)) + geom_bar(stat = "identity") +
  theme_gray(base_size = 15) +
  labs(title = "Total # of Job Postings by Northrop Grumman in Each Occupation Field (2019)",
       x = "Occupation Field",
       y = "Job Count")

# Remove null majors
ng_field <- filter(ng_field, !is.na(major))

# Major breakdown, C1
ng_field %>%
  filter(DETAIL == "C1") %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(major, job_count), y = job_count)) + geom_bar(stat = "identity") +
  theme_gray(base_size = 15) +
  labs(title = "Top 5 Majors in Demand for C1 Jobs by Northrop Grumman (2019)",
       x = "Major",
       y = "Job Count") +
  coord_flip()

# Major breakdown, C2
ng_field %>%
  filter(DETAIL == "C2") %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(major, job_count), y = job_count)) + geom_bar(stat = "identity") +
  theme_gray(base_size = 15) +
  labs(title = "Top 5 Majors in Demand for C2 Jobs by Northrop Grumman (2019)",
       x = "Major",
       y = "Job Count") +
  coord_flip()

# Major breakdown, PT
ng_field %>%
  filter(DETAIL == "PT") %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(major, job_count), y = job_count)) + geom_bar(stat = "identity") +
  theme_gray(base_size = 15) +
  labs(title = "Top 5 Majors in Demand for PT Jobs by Northrop Grumman (2019)",
       x = "Major",
       y = "Job Count") +
  coord_flip()

# Major breakdown, CT
ng_field %>%
  filter(DETAIL == "CT") %>%
  slice(1:5) %>%
  ggplot(aes(x = reorder(major, job_count), y = job_count)) + geom_bar(stat = "identity") +
  theme_gray(base_size = 15) +
  labs(title = "Top 5 Majors in Demand for CT Jobs by Northrop Grumman (2019)",
       x = "Major",
       y = "Job Count") +
  coord_flip()
```


What is their yearly trend, broken down by the occupation field?
```{r}
ng_trend <- read_csv("ng_trend.csv")

ggplot(ng_trend, aes(x = year, y = job_count, color = DETAIL)) +
  geom_line() + geom_point(size = 5) +
  scale_x_continuous(breaks=c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020)) +
  theme_gray(base_size = 15) +
  labs(title = "Trend in AI Labor Demand by Northrop Grumman in Each Occupation Field",
       x = "Year",
       y = "Job Count") +
  scale_color_discrete("AI Occupation Field", breaks = c( "C1", "C2", "PT", "CT"))
```


How does the trend for AI job postings compare to the total job postings?
```{r}
ng_trend_total <- read_csv("ng_trend_total.csv")

# NA = all unrelated AI jobs
# Replace NA with total number of jobs for each year
ng_trend_total %>%
  group_by(year) %>%
  mutate(job_count = ifelse(is.na(DETAIL), sum(job_count), job_count),
         DETAIL = ifelse(is.na(DETAIL), "Total", DETAIL)) %>%
  ggplot(aes(x = year, y = job_count, color = DETAIL)) +
  geom_line() + geom_point(size = 5) +
  scale_x_continuous(breaks=c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020)) +
  theme_gray(base_size = 15) +
  labs(title = "Trend in AI Labor Demand by Northrop Grumman",
       x = "Year",
       y = "Job Count") +
  scale_color_discrete("AI Occupation Field", breaks = c("Total", "C1", "C2", "PT", "CT"))
```

